### PR TITLE
fix: report in case of cyclic dependency

### LINKED ISSUE #267: Bug: When kpm adds a KCL package in the local path as a dependency, circular dependency problem occurs
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. create a kcl package named `aaa`

```
kcl mod init aaa
```

2. create a kcl package named `bbb`

```
kcl mod init bbb
```

3. enter the `aaa` and add the `bbb` as the dependency 

```
cd /usr/kcl/aaa && kcl mod add /usr/kcl/bbb
```

4. enter the `bbb` and add the `aaa` as the dependency 

```
cd /usr/kcl/bbb && kcl mod add /usr/kcl/aaa
```

5. edit the main.k in `aaa` and compile the kcl package `aaa`

the `main.k`
```
import aaa as a
a = 1
```

compile it.

### 2. What did you expect to see? (Required)

The above process causes `aaa` to add itself as a dependency to the `aaa` package, and an error should be reported during the addition of the dependency.

### 3. What did you see instead (Required)

A rust error has been raised.

```
failed to compile the kcl package
called `Option::unwrap()` on a `None` value
```

### 4. What is your KCL components version? (Required)

The main branch of KCL and KPM

### PR DESCRIPTION
**Pull request by AkashKumar7902**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [x] Y

fix #267  

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [x] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Other

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [x] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [ ] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [ ] Other

### CODE REVIEW

File: pkg/client/client_test.go [hunk 1]
```diff
@@ -157,6 +157,10 @@ func TestDependencyGraph(t *testing.T) {
 	)
 }
 
+func TestCyclicDependency(t *testing.T) {
```
Comment (Peefy) [inline pkg/client/client_test.go:160]: The test is empty and CI failed.

Comment (AkashKumar7902) [reply pkg/client/client_test.go:160]: yeah i am working on that test. this test wasn't supposed to be pushed, got committed with other changes on client_test.go
sorry about that

Comment (AkashKumar7902) [reply pkg/client/client_test.go:161]: @Peefy I have added the unit test, i couldn't understand why "windows test" ci is failing. 
image
any insights what went wrong ?

also e2e tests are failing as a cycle exist and now an error is displayed. I can fix the e2e test by changing test_suite.stdout files

File: pkg/client/client_test.go [hunk 2]
```diff
@@ -157,6 +158,34 @@ func TestDependencyGraph(t *testing.T) {
...
+
+	kpmcli, err := NewKpmClient()
+	assert.Equal(t, err, nil)
+	kclPkg, err := kpmcli.LoadPkgFromPath(pkg_path)
+	assert.Equal(t, err, nil)
+
+	currentDir, err := os.Getwd()
+	assert.Equal(t, err, nil)
+	err = os.Chdir(pkg_path)
+	assert.Equal(t, err, nil)
```
Comment (AkashKumar7902) [inline pkg/client/client_test.go:178]: these are done as without it an error is thrown at https://github.com/kcl-lang/kpm/blob/296b6ed4d3658fd9b2701820eed6b5b64a9c0f54/pkg/utils/utils.go#L31

in this function call, `dir` is set to `../b` and it is complaning it can't find the file as it is looking with respect to client folder instead of aaa package folder

File: pkg/client/client.go [hunk 3]
```diff
@@ -1215,37 +1209,31 @@ func (c *KpmClient) downloadDeps(deps pkg.Dependencies, lockDeps pkg.Dependencie
...
 
-		sourcesOfNestedDepGraph, err := pkgGraph.FindSources(nestedDepGraph)
+		err = depGraph.AddEdge(parent, source)
 		if err != nil {
-			return nil, nil, err
+			if err == graph.ErrEdgeCreatesCycle {
+				return nil, reporter.NewErrorEvent(
+					reporter.CircularDependencyExist,
+					nil,
+					"adding dependencies results in a cycle",
```
Comment (Peefy) [inline pkg/client/client.go:1227]: Suggest adding which packages have circular references to the error message to help developers improve dependencies.

Comment (AkashKumar7902) [reply pkg/client/client.go]: done!

File: pkg/client/client_test.go (hunk 2 above)
Comment (Peefy) [reply pkg/client/client_test.go:178]: PR conflcted.

Comment (AkashKumar7902) [reply pkg/client/client_test.go:178]: Solved the merge conflict

File: pkg/client/client_test.go (hunk 1 above)
Comment (AkashKumar7902) [reply pkg/client/client_test.go:162]: passed :+1:
